apiVersion: v1
kind: Pod
metadata:
  name: gocd-elastic-agent-test-{{ POD_POSTFIX }}
  namespace: gocd
spec:
  volumes:
    - name: dockerconfig
      secret:
        secretName: registrypullsecret
        items:
          - key: .dockerconfigjson
            path: config.json
            mode: 511
    - name: gocd-test-github-secret
      secret:
        secretName: gocd-test-github-secret
        defaultMode: 384
    - name: workdir
      emptyDir: {}
    - name: npmrc
      secret:
        secretName: gocd-npmrc-secret
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: ebs-claim
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: vevo/gocd-agent-dind:1.0.6
      env:
      - name: JAVA_HOME
        value: "/usr"
      resources:
        requests:
          memory: "1024M"
      securityContext:
        privileged: true
      volumeMounts:
        - name: gocd-test-github-secret
          mountPath: /root/.ssh/
          readOnly: true
        - name: workdir
          mountPath: /root/.docker/
        - name: npmrc
          mountPath: /etc/.npmrc
          subPath: .npmrc
        - name: persistent-storage
          mountPath: /test
  initContainers:
  - name: configure
    image: alpine
    command: ["/bin/ash","-c","cp /tmp/config.json /work-dir/config.json"]
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
    - name: dockerconfig
      mountPath: "/tmp"
  imagePullSecrets:
    - name: registrypullsecret
  serviceAccountName: mgmt-mgmt-gocd

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  namespace: gocd
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  throughput: "200"
  iops: "4000"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: gocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 100Gi

---
